/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import DAO.LivrosDAO;
import DAO.ReservaDAO;
import collections.ConnectionMod;
import java.util.List;
import javabeans.Livros;
import javabeans.Reservas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JTextField;

/**
 *
 * @author lgera
 */
public class Reserva extends javax.swing.JFrame {
    Connection conecta;
    ResultSet rs;
    PreparedStatement stmt;
    /**
     * Creates new form Reserva
     */
    public void Listar(){
        try {
            LivrosDAO dao = new LivrosDAO();
            List<Livros> listaU = dao.listarLivros();
            DefaultTableModel modelo = (DefaultTableModel)tabelaB.getModel();
            modelo.setNumRows(0);
            
            for(Livros v : listaU){
                modelo.addRow(new Object[]{
                v.getIdlivro(),
                v.getTitulo(),
                v.getAutor(),
                v.getEditora()
                });
            }
        } catch (Exception e) {
        }
    }
    
        public void ListarR(){
            try {
            
            ReservaDAO dao = new ReservaDAO();
            List<Reservas> listaU = dao.listarReserva();
            DefaultTableModel modelo = (DefaultTableModel)tabelaR.getModel();
            modelo.setNumRows(0);
            
            for(Reservas v : listaU){
                modelo.addRow(new Object[]{
                v.getIdreserva(),
                v.getIdliv(),
                v.getTit(),
                v.getDataE(),
                v.getDataR()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro" +e); 
        }
    }
    
    public Reserva() {
        conecta = new ConnectionMod().conecta();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaR = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtCodL = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaB = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDataE = new com.toedter.calendar.JDateChooser();
        txtDataR = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtTit = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Área de reserva de livros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 240, -1));

        txtBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusActionPerformed(evt);
            }
        });
        getContentPane().add(txtBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 85, 220, 30));

        tabelaR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID reserva", "Código do livro", "Titulo", "Data de reserva", "Data de fim de reserva"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaRMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaR);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 520, 80));

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 530, 20));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setText("Código do livro: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        txtCodL.setEditable(false);
        txtCodL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodLActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 160, -1));

        jButton2.setText("RESERVAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        tabelaB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Titulo", "Autor", "Editora"
            }
        ));
        tabelaB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaBMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaB);
        if (tabelaB.getColumnModel().getColumnCount() > 0) {
            tabelaB.getColumnModel().getColumn(2).setHeaderValue("Usuário");
            tabelaB.getColumnModel().getColumn(3).setHeaderValue("Editora");
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 380, 90));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel6.setText("Data de reserva: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel7.setText("Data de fim de reserva: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));
        getContentPane().add(txtDataE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 160, -1));
        getContentPane().add(txtDataR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 160, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Titulo: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        txtTit.setEditable(false);
        txtTit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitActionPerformed(evt);
            }
        });
        getContentPane().add(txtTit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 160, -1));

        jButton3.setText("CANCELAR RESERVA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Listar();
    }//GEN-LAST:event_formWindowActivated

    private void txtCodLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodLActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                 
        String cmdsql = "insert into reserva(idliv,titulo,dataE,dataR) values(?,?,?,?)";
        
        try {
            
            stmt = conecta.prepareStatement(cmdsql);
            
            stmt.setInt(1, Integer.parseInt(txtCodL.getText()));
            stmt.setString(2, txtTit.getText());
            stmt.setString(3, ((JTextField)txtDataE.getDateEditor().getUiComponent()).getText());
            stmt.setString(4, ((JTextField)txtDataR.getDateEditor().getUiComponent()).getText());
            
            stmt.execute();
            
            JOptionPane.showMessageDialog(null, "reservado com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro na reserva " +e);
        }
        ListarR();
        
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabelaRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaRMouseClicked
        txtCodL.setText(tabelaR.getValueAt(tabelaR.getSelectedRow(), 0).toString());
        txtTit.setText(tabelaR.getValueAt(tabelaR.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tabelaRMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String titulo = txtBus.getText();
            
            
            LivrosDAO dao = new LivrosDAO();
            List<Livros> listaU = dao.listarLivrosPorTit(titulo);
            DefaultTableModel modelo = (DefaultTableModel)tabelaB.getModel();
            modelo.setNumRows(0);
            
            for(Livros v : listaU){
                modelo.addRow(new Object[]{
                v.getIdlivro(),
                v.getTitulo(),
                v.getAutor(),
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Livro não encontrado"); 
        }
        limpar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaBMouseClicked
        txtCodL.setText(tabelaB.getValueAt(tabelaB.getSelectedRow(), 0).toString());
        txtTit.setText(tabelaB.getValueAt(tabelaB.getSelectedRow(), 1).toString());
        
    }//GEN-LAST:event_tabelaBMouseClicked

    private void txtTitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            Reservas obj = new Reservas();
            
            obj.setIdreserva(Integer.parseInt(txtCodL.getText()));

            ReservaDAO dao = new ReservaDAO();
            dao.excluirReserva(obj);

            JOptionPane.showMessageDialog(null, "Excluido com sucesso");
            ListarR();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "falha" + e); 
        }
        limpar();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public void limpar(){
        txtBus.setText("");
        txtCodL.setText("");
        txtTit.setText("");
        txtBus.requestFocus();   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaB;
    private javax.swing.JTable tabelaR;
    private javax.swing.JTextField txtBus;
    private javax.swing.JTextField txtCodL;
    private com.toedter.calendar.JDateChooser txtDataE;
    private com.toedter.calendar.JDateChooser txtDataR;
    private javax.swing.JTextField txtTit;
    // End of variables declaration//GEN-END:variables
}
